version: '3'

services:
  web:
    image: controle_atividades:0.0.1
    build: .
    command: ./runserver
    volumes:
      - ".:/controle_atividades"
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:10.3
