# Generated by Django 2.2.1 on 2019-05-01 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=3)),
                ('p_acertos', models.DecimalField(decimal_places=2, max_digits=3)),
                ('aula', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perg', models.TextField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa', models.TextField()),
                ('opcao', models.CharField(max_length=1)),
                ('situacao', models.BooleanField(default=False)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categoria')),
                ('perg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pergunta')),
            ],
        ),
    ]
