# Generated by Django 2.2 on 2019-05-07 00:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(verbose_name='Hora de início')),
            ],
            options={
                'verbose_name': 'Ativiade',
                'verbose_name_plural': 'Ativiades',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('period', models.CharField(choices=[('morning', 'Manhã'), ('afternoon', 'Tarde'), ('night', 'Noite')], max_length=50, verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('subscription', models.CharField(max_length=50, verbose_name='Inscrição')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Estudante',
                'verbose_name_plural': 'Estudantes',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('value_question', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor da pergunta')),
                ('alternatives', models.CharField(choices=[('a', 'A)'), ('b', 'B)'), ('c', 'C)'), ('d', 'D)')], max_length=50, verbose_name='Alternativas')),
                ('correct_alternative', models.CharField(max_length=50, verbose_name='Alternativa Correta')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Activity')),
            ],
            options={
                'verbose_name': 'Questions',
                'verbose_name_plural': 'Questionss',
            },
        ),
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Students')),
            ],
            options={
                'verbose_name': 'Nota Final',
                'verbose_name_plural': 'Notas Finais',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Course'),
        ),
    ]
