# Generated by Django 2.2.1 on 2019-05-01 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='p_acertos',
            new_name='porcentagem_acertos',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='cat',
            new_name='categoria',
        ),
    ]
