# Generated by Django 2.2 on 2019-05-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.RemoveField(
            model_name='questions',
            name='alternatives',
        ),
        migrations.AlterField(
            model_name='questions',
            name='correct_alternative',
            field=models.CharField(choices=[('a', 'A)'), ('b', 'B)'), ('c', 'C)'), ('d', 'D)')], max_length=50, verbose_name='Alternativa Correta'),
        ),
    ]
