# Generated by Django 2.2 on 2019-05-07 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190506_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalgrade',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Activity', verbose_name='Atividade'),
        ),
        migrations.AlterField(
            model_name='finalgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Students', verbose_name='Estudante'),
        ),
    ]
