# Generated by Django 2.2 on 2019-06-25 23:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_students_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='subscription',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
