# Generated by Django 2.2 on 2019-06-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190625_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='subscription',
            field=models.CharField(max_length=50, verbose_name='Inscrição'),
        ),
    ]
