# Generated by Django 2.2 on 2019-06-25 23:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190625_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='subscription',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
    ]
