# Generated by Django 2.2 on 2019-06-26 00:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190625_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='subscription',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=8),
        ),
    ]
