# Generated by Django 2.2 on 2019-08-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190730_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='core.Students', verbose_name='Estudantes'),
        ),
    ]
