# Generated by Django 2.2 on 2019-08-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190810_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='core.Students', verbose_name='Estudantes'),
        ),
    ]
