# Generated by Django 2.2 on 2019-08-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_questions_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='core.Students', verbose_name='Estudantes'),
        ),
    ]
