# Generated by Django 2.2 on 2019-08-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190810_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviação'),
        ),
    ]
